### ISSUE TITLE
SteamGuardAccount.FetchConfirmations() throws WGTokenInvalidException

### ISSUE THREAD

**Issue by alex-jin** [geel9/SteamAuth#36]
Hi, about half month ago, I am able to use FetchConfirmations to get confirmation list and accept those confirmations. But now FetchConfirmations can't work. could you please take a look? Thanks in advance.

**Comment by alex-jin** [comment]
I added 
SteamGuardAccount.Session.SteamLogin = SteamWeb.Token;
                SteamGuardAccount.Session.SteamLoginSecure = SteamWeb.TokenSecure;

before calling FetchConfirmations  and problem solved.

**Comment by Prosto-Sanja** [comment]
alex-jin, can you help me please, i dont have any token and tokensecure in steamweb

**Comment by Prosto-Sanja** [comment]
hello,  SteamGuardAccount.RefreshSession(); solved the problem, best luck guys!

**Comment by mik13ST** [comment]
If RefreshSession() does not solve the problem (returns false, because WebException) and you are executing the exe on RaspberryPi using Mono thru a PHP script (like I am :smiley: ), then you might be missing HTTPS (SSL) certificates. This can be ignored (since we write the code and know who to trust) by implementing [method #1](http://www.mono-project.com/archived/usingtrustedrootsrespectfully/#appendix-approach--1-actively-ignore-security-concerns-) from official Mono documentation guide to solving missing certificates.
